Importações:

In [1]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
estatisticas = "campeonato-brasileiro-estatisticas-full.csv"
full = "campeonato-brasileiro-full.csv"
# Load the latest version
df_estats = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "adaoduque/campeonato-brasileiro-de-futebol",
  estatisticas,

)

df_full = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "adaoduque/campeonato-brasileiro-de-futebol",
  full,
)

display(df_estats.head())
display(df_full.head())

d:\Desktop\PROJETO CAIXAVERSO\Caixaverso-FC5\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\celso\AppData\Local\Temp\ipykernel_3020\3277659839.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df_estats = kagglehub.load_dataset(
C:\Users\celso\AppData\Local\Temp\ipykernel_3020\3277659839.py:17: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df_full = kagglehub.load_dataset(

,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios
0,1,1,Vasco,0,0,NaN,0,NaN,0,0,0,0,0
1,1,1,Guarani,0,0,NaN,0,NaN,0,0,0,0,0
2,2,1,Athletico-PR,0,0,NaN,0,NaN,0,0,0,0,0
3,2,1,Gremio,0,0,NaN,0,NaN,0,0,0,0,0
4,3,1,Flamengo,0,0,NaN,0,NaN,0,0,0,0,0

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado,arrecadacao
0,1,1,29/03/2003,16:00,Guarani,Vasco,NaN,NaN,NaN,NaN,Guarani,Brinco de Ouro,4,2,SP,RJ,NaN
1,2,1,29/03/2003,16:00,Athletico-PR,Gremio,NaN,NaN,NaN,NaN,Athletico-PR,Arena da Baixada,2,0,PR,RS,NaN
2,3,1,30/03/2003,16:00,Flamengo,Coritiba,NaN,NaN,NaN,NaN,-,Maracanã,1,1,RJ,PR,NaN
3,4,1,30/03/2003,16:00,Goias,Paysandu,NaN,NaN,NaN,NaN,-,Serra Dourada,2,2,GO,PA,NaN
4,5,1,30/03/2003,16:00,Internacional,Ponte Preta,NaN,NaN,NaN,NaN,-,Beira Rio,1,1,RS,SP,NaN

In [2]:
print(f"Shape do df_estats: {df_estats.shape}")
print(f"Shape do df_full: {df_full.shape}")

Shape do df_estats: (18330, 13)
Shape do df_full: (9165, 17)

In [3]:
df_estats.info()
df_full.info()

<class 'pandas.DataFrame'>
RangeIndex: 18330 entries, 0 to 18329
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   partida_id       18330 non-null  int64
 1   rodata           18330 non-null  int64
 2   clube            18330 non-null  str
 3   chutes           18330 non-null  int64
 4   chutes_no_alvo   18330 non-null  int64
 5   posse_de_bola    7568 non-null   str
 6   passes           18330 non-null  int64
 7   precisao_passes  5264 non-null   str
 8   faltas           18330 non-null  int64
 9   cartao_amarelo   18330 non-null  int64
 10  cartao_vermelho  18330 non-null  int64
 11  impedimentos     18330 non-null  int64
 12  escanteios       18330 non-null  int64
dtypes: int64(10), str(3)
memory usage: 1.8 MB
<class 'pandas.DataFrame'>
RangeIndex: 9165 entries, 0 to 9164
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  9165 non-null   int64
 1   rodata              9165 non-null   int64
 2   data                9165 non-null   str
 3   hora                9165 non-null   str
 4   mandante            9165 non-null   str
 5   visitante           9165 non-null   str
 6   formacao_mandante   4190 non-null   str
 7   formacao_visitante  4190 non-null   str
 8   tecnico_mandante    4555 non-null   str
 9   tecnico_visitante   4555 non-null   str
 10  vencedor            9165 non-null   str
 11  arena               9165 non-null   str
 12  mandante_Placar     9165 non-null   int64
 13  visitante_Placar    9165 non-null   int64
 14  mandante_Estado     9165 non-null   str
 15  visitante_Estado    9165 non-null   str
 16  arrecadacao         380 non-null    float64
dtypes: float64(1), int64(4), str(12)
memory usage: 1.2 MB